services:

  app:
    depends_on: [db]
    image: cabyca/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 5 && npm test'
    environment:
    - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
    - DATABASE_NAME=${DATABASE_NAME:-postgres}
    - DATABASE_HOST=${DATABASE_HOST:-db}

  db:
    image: postgres:16
    restart: always
    environment:
    - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password}
    - POSTGRES_DB=${DATABASE_NAME:-postgres}
