services:

  app:
    depends_on: [db]
    image: dev
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./app:/app
#    command: npm run dev
    env_file:
      - .env
    command: bash -c 'sleep 3 && npm start'    
    ports:
      - "8080:8080"

  caddy:
    depends_on: [app]
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile 
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  db:
    image: postgres:latest
    restart: always
    environment:
    - POSTGRES_USER=${DATABASE_USERNAME}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    - POSTGRES_DB=${DATABASE_NAME}

    ports:
      - "5432:5432"

volumes:
  caddy_data:
    external: true
  caddy_config:
