services:
  app:
    depends_on: [db]
    image: cabyca/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

