services:
  app:
    depends_on: [db]
    image: cabyca/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    environment:
    - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
    - DATABASE_NAME=${DATABASE_NAME:-postgres}
    - DATABASE_HOST=${DATABASE_HOST:-db}

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
