# file: .github/workflows/push.yml
name: push in docker-hub
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  tests:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - name: tests
        uses: actions/checkout@v3
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
        run: make ci
  build:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: actions/checkout@v3
        run: make build
